# Generated by Django 5.2.8 on 2025-12-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog/previews/", verbose_name="Превью"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
            ],
            options={
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
                "ordering": ["-created_at"],
            },
        ),
    ]
