# Generated by Django 5.2.8 on 2025-12-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
