# Generated by Django 5.2.8 on 2025-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(default="", verbose_name="Описание категории"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="", verbose_name="Описание продукта"),
        ),
    ]
