# Generated by Django 5.2.8 on 2026-01-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_description_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                blank=True, default=False, help_text="Отметьте, чтобы опубликовать продукт", null=True
            ),
        ),
    ]
